### PR TITLE
Typo fix

### PR DESCRIPTION
**Pull request by BenMorel**

### CODE REVIEW

**Review by chaals — APPROVED** [review]
thanks

**Comment by chaals** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by chaals** [comment]
This spec is among those W3C has currently handed to WHATWG. (They have a version in their HTML spec, that doesn't match reality, which was the motivation for taking this up. I presume the plan is to adopt the content of this spec).

**Comment by BenMorel** [comment]
@chaals Thanks!
I have a few more typo fixes to suggest, however I'm not sure how I should understand your comment above; is it worth submitting there here, or is there another authoritative repo where the official spec now lies?

**Comment by chaals** [comment]
The official spec is now going to be based on https://github.com/whatwg/html/

That is currently somewhat out of date with actual implementations as we tested them in developing this version, and I don't know what the plans are although it seems someone has worked on that section.

As far as I know whatwg still tries to avoid taking any actual text from W3C work - if that is still so there probably isn't much point fixing typos under the current arrangements. 

@annevk, @marcoscaceres or @LJWatson probably know more...

**Comment by annevk** [comment]
If there are tests, conforming implementations, and correct specification text, creating a PR against whatwg/html will be some work, but hopefully not too much? https://participate.whatwg.org/agreement will have to be signed by whoever makes the contribution.

**Pull request merged**
